### ISSUE TITLE
Incorrect taskbar styles in Linux Mint 19

### ISSUE THREAD

**Issue by SkylerGhostly** [B00merang-Project/Windows-10-Dark#17]
I've used the transpack.sh file to install the theme as instructed and have the theme working for the most part. But it seems some of the icons aren't working. The start menu icon, the notification center icon, and the taskbar icons aren't using the windows 10 style for active taskbar items or inactive taskbar items. Other than that, the theme works fine. Maybe in Cinnamon 4+ they changed how the folders are structured? 

![Screenshot from 2019-08-13 15-02-12](https://user-images.githubusercontent.com/38995283/62977185-8ea24f00-bddb-11e9-851d-fd566e3c8d2c.png)

Any help would be much appreciated, thank you! 

Linux Mint 19 Tessa 64bit
Cinnamon 4.0.10+tessa
GTK 3.22

**Comment by Elbullazul** [comment]
you have to manually set the start menu icon:

1. right-click on the menu button > properties
2. check custom image  > go to ~/.themes/Windows-10/cinnamon, select menu.png
3. save

notification center, I don't know if they changed it but last time I used cinnamon you had to override the applet icons in /usr/share/cinnamon/applets/notification-whatever/

what taskbar icons are you talking about? do you mean the selected background doesn't look like this?
![win-10-taskbar](https://www.howtogeek.com/wp-content/uploads/2019/02/VirtualBox_Windows-10-Pro-1803_01_02_2019_01_24_44.png)

**Comment by SkylerGhostly** [comment]
I've been able to change the icon for the start menu myself using your method above, and I can give the notification center a try. And yes, I was talking about the selected background not working. I can see they in the cinnamon.css they you've changed the icons and everything, but it seems to have no effect. Is there something I'm perhaps doing wrong?

**Comment by Elbullazul** [comment]
@SkylerMews I'm afraid you can't realy do something, unless you're familiar with CSS and create a new theme since the current one is partially deprecated by the new Cinnamon versions.

I'll try to make some changes but can't promise anything

**Comment by SkylerGhostly** [comment]
@Elbullazul I'm decently okay with CSS and whatnot, but my issue is ... I'm not even sure where to get the class names or ID names for the UI of Cinnamon. From what it seems like to me, I've edited your Cinnamon CSS file and some of the class names you use appear to be the same as the ones used in the official themes. If there was a better way for me to find the class names, I could write a fix for linux mint to make all the icons work out of the box?

**Comment by Elbullazul** [comment]
https://github.com/linuxmint/mint-themes/tree/master/src/Mint-Y/cinnamon

good luck...

**Comment by Elbullazul** [comment]
BTW had a quick look at it and I'd search for something along the lines of `.grouped-window-list`

as that isn't in the code right now

**Comment by SkylerGhostly** [comment]
@Elbullazul That's exactly what I had found. They changed the name of it. I did a quick replace in the Cinnamon.css file and replaced `.window-list` with `.grouped-window-list` And that seems to have fixed the issue with the item backgrounds not working. It's possible that the old code and the new code could be left side-by-side and would work for the new version of Cinnamon and the older version that it's currently designed for.
![Screenshot from 2019-08-14 12-50-55](https://user-images.githubusercontent.com/38995283/63047875-8822de80-be92-11e9-93e6-c8da045fb939.png)

**Comment by Elbullazul** [comment]
@SkylerMews does the focused window have a different background?

can't test right now

**Comment by SkylerGhostly** [comment]
@Elbullazul It seems that the hover works fine, but I see no difference between when a window is in focus as in, the window is currently being used, and when the window is minimized. And it also seems that when an application isn't open, it still has the blue bar below it. So it seems a bit more time in the oven is needed. So not as simple as I was hoping, as usual with CSS.

**Comment by Elbullazul** [comment]
@SkylerMews 

try adding
```css
  .grouped-window-list-item-box:hover, .grouped-window-list-item-box:focus {
    color: #ffffff;
    background-color: rgba(255, 255, 255, 0.3); }
  .grouped-window-list-item-box:active, .grouped-window-list-item-box:checked {
    color: #00ff00;
    border-color: #ff0000; }
```

**Comment by SkylerGhostly** [comment]
@Elbullazul Now it seems they're changing states by opposite of what they should be. At least to me. The blue bar seems to go away when the application isn't open and I hover OVER it, but the blue bar is still there when the application isn't open and I'm not hovering over it.

EDIT: now that I look at it, it seems all the states are inverted.

**Comment by SkylerGhostly** [comment]
@Elbullazul Any updates or anything?

**Comment by Elbullazul** [comment]
how about 

```css
.grouped-window-list-item-box {
    color: #ffffff;
    font-weight: normal;
    border-image: none;
    transition-duration: 100;
}

.grouped-window-list-item-box:hover, .grouped-window-list-item-box:focus {
    color: #ffffff;
    border-image:url("panel-assets/bottom-item-active-hover.svg.svg") 4;
    transition-duration: 100;
}

.grouped-window-list-item-box:active, .grouped-window-list-item-box:checked {
    color: #ffffff;
    border-image:url("panel-assets/bottom-item-active.svg") 4;
    transition-duration: 100;
}
```
