### ISSUE TITLE
Any custom panel color for cinnamon?

### ISSUE THREAD

**Issue by GitUser445** [B00merang-Project/Windows-10-Dark#28]
![Screenshot from 2020-07-14 19-13-30](https://user-images.githubusercontent.com/54332580/87485214-40f31f80-c606-11ea-8404-1005c4bccb4e.png)
That is ugly as fuck. Is there any way I can change the panel color? I believe there was also an issue about this, but I have cinnamon. Could it work this way? I want it at least to be lighter than the EXACT same color. LM 19.3 Cinnamon. I'm no techie btw.

**Comment by dominichayesferen** [comment]
In cinnamon.css (the theme/cinnamon/cinnamon.css), the panel background is the background value of the #panel area.

**Comment by Elbullazul** [comment]
@GitUser445 

what color do you want to use? I'll post a snippet you can use to change that with instructions afterwards

**Comment by GitUser445** [comment]
@Elbullazul 
#2e2e2e is the hex code for it. just anything other than the same dark black as my wallpaper 0_0.

**Comment by Elbullazul** [comment]
in cinnamon/cinnamon.css, replace

```css
#panel {
  background-color: rgba(0, 0, 0, 0.65);
  ...
}
```

with

```css
#panel {
  background-color: #2e2e2e;
  ...
}
```
